//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace GestorDocument.DAL
{
    public partial class CAT_TIPO_DETERMINANTE
    {
        #region Primitive Properties
    
        public virtual long IdTipoDeterminante
        {
            get;
            set;
        }
    
        public virtual string TipoDeterminanteName
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<CAT_DETERMINANTE> CAT_DETERMINANTE
        {
            get
            {
                if (_cAT_DETERMINANTE == null)
                {
                    var newCollection = new FixupCollection<CAT_DETERMINANTE>();
                    newCollection.CollectionChanged += FixupCAT_DETERMINANTE;
                    _cAT_DETERMINANTE = newCollection;
                }
                return _cAT_DETERMINANTE;
            }
            set
            {
                if (!ReferenceEquals(_cAT_DETERMINANTE, value))
                {
                    var previousValue = _cAT_DETERMINANTE as FixupCollection<CAT_DETERMINANTE>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCAT_DETERMINANTE;
                    }
                    _cAT_DETERMINANTE = value;
                    var newValue = value as FixupCollection<CAT_DETERMINANTE>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCAT_DETERMINANTE;
                    }
                }
            }
        }
        private ICollection<CAT_DETERMINANTE> _cAT_DETERMINANTE;

        #endregion
        #region Association Fixup
    
        private void FixupCAT_DETERMINANTE(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CAT_DETERMINANTE item in e.NewItems)
                {
                    item.CAT_TIPO_DETERMINANTE = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CAT_DETERMINANTE item in e.OldItems)
                {
                    if (ReferenceEquals(item.CAT_TIPO_DETERMINANTE, this))
                    {
                        item.CAT_TIPO_DETERMINANTE = null;
                    }
                }
            }
        }

        #endregion
    }
}
