//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace GestorDocument.DAL
{
    public partial class REL_DESTINATARIO_CCP
    {
        #region Primitive Properties
    
        public virtual long IdDestinatarioCcp
        {
            get;
            set;
        }
    
        public virtual long IdRol
        {
            get { return _idRol; }
            set
            {
                if (_idRol != value)
                {
                    if (APP_ROL != null && APP_ROL.IdRol != value)
                    {
                        APP_ROL = null;
                    }
                    _idRol = value;
                }
            }
        }
        private long _idRol;
    
        public virtual long IdAsunto
        {
            get { return _idAsunto; }
            set
            {
                if (_idAsunto != value)
                {
                    if (GET_ASUNTO != null && GET_ASUNTO.IdAsunto != value)
                    {
                        GET_ASUNTO = null;
                    }
                    _idAsunto = value;
                }
            }
        }
        private long _idAsunto;
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual APP_ROL APP_ROL
        {
            get { return _aPP_ROL; }
            set
            {
                if (!ReferenceEquals(_aPP_ROL, value))
                {
                    var previousValue = _aPP_ROL;
                    _aPP_ROL = value;
                    FixupAPP_ROL(previousValue);
                }
            }
        }
        private APP_ROL _aPP_ROL;
    
        public virtual GET_ASUNTO GET_ASUNTO
        {
            get { return _gET_ASUNTO; }
            set
            {
                if (!ReferenceEquals(_gET_ASUNTO, value))
                {
                    var previousValue = _gET_ASUNTO;
                    _gET_ASUNTO = value;
                    FixupGET_ASUNTO(previousValue);
                }
            }
        }
        private GET_ASUNTO _gET_ASUNTO;

        #endregion
        #region Association Fixup
    
        private void FixupAPP_ROL(APP_ROL previousValue)
        {
            if (previousValue != null && previousValue.REL_DESTINATARIO_CCP.Contains(this))
            {
                previousValue.REL_DESTINATARIO_CCP.Remove(this);
            }
    
            if (APP_ROL != null)
            {
                if (!APP_ROL.REL_DESTINATARIO_CCP.Contains(this))
                {
                    APP_ROL.REL_DESTINATARIO_CCP.Add(this);
                }
                if (IdRol != APP_ROL.IdRol)
                {
                    IdRol = APP_ROL.IdRol;
                }
            }
        }
    
        private void FixupGET_ASUNTO(GET_ASUNTO previousValue)
        {
            if (previousValue != null && previousValue.REL_DESTINATARIO_CCP.Contains(this))
            {
                previousValue.REL_DESTINATARIO_CCP.Remove(this);
            }
    
            if (GET_ASUNTO != null)
            {
                if (!GET_ASUNTO.REL_DESTINATARIO_CCP.Contains(this))
                {
                    GET_ASUNTO.REL_DESTINATARIO_CCP.Add(this);
                }
                if (IdAsunto != GET_ASUNTO.IdAsunto)
                {
                    IdAsunto = GET_ASUNTO.IdAsunto;
                }
            }
        }

        #endregion
    }
}
