//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Dal.Pocos
{
    public partial class APP_USUARIO_ROL
    {
        #region Primitive Properties
    
        public virtual long IdUsuarioRol
        {
            get;
            set;
        }
    
        public virtual long IdUsuario
        {
            get { return _idUsuario; }
            set
            {
                if (_idUsuario != value)
                {
                    if (APP_USUARIO != null && APP_USUARIO.IdUsuario != value)
                    {
                        APP_USUARIO = null;
                    }
                    _idUsuario = value;
                }
            }
        }
        private long _idUsuario;
    
        public virtual long IdRol
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual APP_USUARIO APP_USUARIO
        {
            get { return _aPP_USUARIO; }
            set
            {
                if (!ReferenceEquals(_aPP_USUARIO, value))
                {
                    var previousValue = _aPP_USUARIO;
                    _aPP_USUARIO = value;
                    FixupAPP_USUARIO(previousValue);
                }
            }
        }
        private APP_USUARIO _aPP_USUARIO;

        #endregion
        #region Association Fixup
    
        private void FixupAPP_USUARIO(APP_USUARIO previousValue)
        {
            if (previousValue != null && previousValue.APP_USUARIO_ROL.Contains(this))
            {
                previousValue.APP_USUARIO_ROL.Remove(this);
            }
    
            if (APP_USUARIO != null)
            {
                if (!APP_USUARIO.APP_USUARIO_ROL.Contains(this))
                {
                    APP_USUARIO.APP_USUARIO_ROL.Add(this);
                }
                if (IdUsuario != APP_USUARIO.IdUsuario)
                {
                    IdUsuario = APP_USUARIO.IdUsuario;
                }
            }
        }

        #endregion
    }
}
