//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Dal.Pocos
{
    public partial class APP_ROL
    {
        #region Primitive Properties
    
        public virtual long IdRol
        {
            get;
            set;
        }
    
        public virtual string RolName
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<GET_TURNO> GET_TURNO
        {
            get
            {
                if (_gET_TURNO == null)
                {
                    var newCollection = new FixupCollection<GET_TURNO>();
                    newCollection.CollectionChanged += FixupGET_TURNO;
                    _gET_TURNO = newCollection;
                }
                return _gET_TURNO;
            }
            set
            {
                if (!ReferenceEquals(_gET_TURNO, value))
                {
                    var previousValue = _gET_TURNO as FixupCollection<GET_TURNO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGET_TURNO;
                    }
                    _gET_TURNO = value;
                    var newValue = value as FixupCollection<GET_TURNO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGET_TURNO;
                    }
                }
            }
        }
        private ICollection<GET_TURNO> _gET_TURNO;
    
        public virtual ICollection<INF_INFODOC> INF_INFODOC
        {
            get
            {
                if (_iNF_INFODOC == null)
                {
                    var newCollection = new FixupCollection<INF_INFODOC>();
                    newCollection.CollectionChanged += FixupINF_INFODOC;
                    _iNF_INFODOC = newCollection;
                }
                return _iNF_INFODOC;
            }
            set
            {
                if (!ReferenceEquals(_iNF_INFODOC, value))
                {
                    var previousValue = _iNF_INFODOC as FixupCollection<INF_INFODOC>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupINF_INFODOC;
                    }
                    _iNF_INFODOC = value;
                    var newValue = value as FixupCollection<INF_INFODOC>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupINF_INFODOC;
                    }
                }
            }
        }
        private ICollection<INF_INFODOC> _iNF_INFODOC;
    
        public virtual ICollection<REL_DESTINATARIO> REL_DESTINATARIO
        {
            get
            {
                if (_rEL_DESTINATARIO == null)
                {
                    var newCollection = new FixupCollection<REL_DESTINATARIO>();
                    newCollection.CollectionChanged += FixupREL_DESTINATARIO;
                    _rEL_DESTINATARIO = newCollection;
                }
                return _rEL_DESTINATARIO;
            }
            set
            {
                if (!ReferenceEquals(_rEL_DESTINATARIO, value))
                {
                    var previousValue = _rEL_DESTINATARIO as FixupCollection<REL_DESTINATARIO>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupREL_DESTINATARIO;
                    }
                    _rEL_DESTINATARIO = value;
                    var newValue = value as FixupCollection<REL_DESTINATARIO>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupREL_DESTINATARIO;
                    }
                }
            }
        }
        private ICollection<REL_DESTINATARIO> _rEL_DESTINATARIO;
    
        public virtual ICollection<REL_DESTINATARIO_CCP> REL_DESTINATARIO_CCP
        {
            get
            {
                if (_rEL_DESTINATARIO_CCP == null)
                {
                    var newCollection = new FixupCollection<REL_DESTINATARIO_CCP>();
                    newCollection.CollectionChanged += FixupREL_DESTINATARIO_CCP;
                    _rEL_DESTINATARIO_CCP = newCollection;
                }
                return _rEL_DESTINATARIO_CCP;
            }
            set
            {
                if (!ReferenceEquals(_rEL_DESTINATARIO_CCP, value))
                {
                    var previousValue = _rEL_DESTINATARIO_CCP as FixupCollection<REL_DESTINATARIO_CCP>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupREL_DESTINATARIO_CCP;
                    }
                    _rEL_DESTINATARIO_CCP = value;
                    var newValue = value as FixupCollection<REL_DESTINATARIO_CCP>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupREL_DESTINATARIO_CCP;
                    }
                }
            }
        }
        private ICollection<REL_DESTINATARIO_CCP> _rEL_DESTINATARIO_CCP;

        #endregion
        #region Association Fixup
    
        private void FixupGET_TURNO(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GET_TURNO item in e.NewItems)
                {
                    item.APP_ROL = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GET_TURNO item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_ROL, this))
                    {
                        item.APP_ROL = null;
                    }
                }
            }
        }
    
        private void FixupINF_INFODOC(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (INF_INFODOC item in e.NewItems)
                {
                    item.APP_ROL = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (INF_INFODOC item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_ROL, this))
                    {
                        item.APP_ROL = null;
                    }
                }
            }
        }
    
        private void FixupREL_DESTINATARIO(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (REL_DESTINATARIO item in e.NewItems)
                {
                    item.APP_ROL = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REL_DESTINATARIO item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_ROL, this))
                    {
                        item.APP_ROL = null;
                    }
                }
            }
        }
    
        private void FixupREL_DESTINATARIO_CCP(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (REL_DESTINATARIO_CCP item in e.NewItems)
                {
                    item.APP_ROL = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (REL_DESTINATARIO_CCP item in e.OldItems)
                {
                    if (ReferenceEquals(item.APP_ROL, this))
                    {
                        item.APP_ROL = null;
                    }
                }
            }
        }

        #endregion
    }
}
