//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Dal.Pocos
{
    public partial class CAT_ORGANIGRAMA
    {
        #region Primitive Properties
    
        public virtual long IdJerarquia
        {
            get;
            set;
        }
    
        public virtual Nullable<long> IdJerarquiaParent
        {
            get;
            set;
        }
    
        public virtual string JerarquiaName
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<long> LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsModified
        {
            get;
            set;
        }
    
        public virtual long IdRol
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<long> IdTipoUnidadNormativa
        {
            get { return _idTipoUnidadNormativa; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_idTipoUnidadNormativa != value)
                    {
                        if (CAT_TIPO_UNIDAD_NORMATIVA != null && CAT_TIPO_UNIDAD_NORMATIVA.IdTipoUnidadNormativa != value)
                        {
                            CAT_TIPO_UNIDAD_NORMATIVA = null;
                        }
                        _idTipoUnidadNormativa = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _idTipoUnidadNormativa;
    
        public virtual string JerarquiaTitular
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CAT_TIPO_UNIDAD_NORMATIVA CAT_TIPO_UNIDAD_NORMATIVA
        {
            get { return _cAT_TIPO_UNIDAD_NORMATIVA; }
            set
            {
                if (!ReferenceEquals(_cAT_TIPO_UNIDAD_NORMATIVA, value))
                {
                    var previousValue = _cAT_TIPO_UNIDAD_NORMATIVA;
                    _cAT_TIPO_UNIDAD_NORMATIVA = value;
                    FixupCAT_TIPO_UNIDAD_NORMATIVA(previousValue);
                }
            }
        }
        private CAT_TIPO_UNIDAD_NORMATIVA _cAT_TIPO_UNIDAD_NORMATIVA;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCAT_TIPO_UNIDAD_NORMATIVA(CAT_TIPO_UNIDAD_NORMATIVA previousValue)
        {
            if (previousValue != null && previousValue.CAT_ORGANIGRAMA.Contains(this))
            {
                previousValue.CAT_ORGANIGRAMA.Remove(this);
            }
    
            if (CAT_TIPO_UNIDAD_NORMATIVA != null)
            {
                if (!CAT_TIPO_UNIDAD_NORMATIVA.CAT_ORGANIGRAMA.Contains(this))
                {
                    CAT_TIPO_UNIDAD_NORMATIVA.CAT_ORGANIGRAMA.Add(this);
                }
                if (IdTipoUnidadNormativa != CAT_TIPO_UNIDAD_NORMATIVA.IdTipoUnidadNormativa)
                {
                    IdTipoUnidadNormativa = CAT_TIPO_UNIDAD_NORMATIVA.IdTipoUnidadNormativa;
                }
            }
            else if (!_settingFK)
            {
                IdTipoUnidadNormativa = null;
            }
        }

        #endregion
    }
}
