//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Dal.Pocos
{
    public partial class GET_DOCUMENTOS
    {
        #region Primitive Properties
    
        public virtual long IdDocumento
        {
            get;
            set;
        }
    
        public virtual string DocumentoName
        {
            get;
            set;
        }
    
        public virtual string DocumentoPath
        {
            get;
            set;
        }
    
        public virtual string Extencion
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual Nullable<long> IdTurno
        {
            get { return _idTurno; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_idTurno != value)
                    {
                        if (GET_TURNO != null && GET_TURNO.IdTurno != value)
                        {
                            GET_TURNO = null;
                        }
                        _idTurno = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _idTurno;
    
        public virtual Nullable<System.DateTime> Fecha
        {
            get;
            set;
        }
    
        public virtual long IdExpediente
        {
            get { return _idExpediente; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_idExpediente != value)
                    {
                        if (GET_EXPEDIENTE != null && GET_EXPEDIENTE.IdExpediente != value)
                        {
                            GET_EXPEDIENTE = null;
                        }
                        _idExpediente = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private long _idExpediente;
    
        public virtual long IdTipoDocumento
        {
            get { return _idTipoDocumento; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_idTipoDocumento != value)
                    {
                        if (CAT_TIPO_DOCUMENTO != null && CAT_TIPO_DOCUMENTO.IdTipoDocumento != value)
                        {
                            CAT_TIPO_DOCUMENTO = null;
                        }
                        _idTipoDocumento = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private long _idTipoDocumento;
    
        public virtual Nullable<bool> IsDocumentoOriginal
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual CAT_TIPO_DOCUMENTO CAT_TIPO_DOCUMENTO
        {
            get { return _cAT_TIPO_DOCUMENTO; }
            set
            {
                if (!ReferenceEquals(_cAT_TIPO_DOCUMENTO, value))
                {
                    var previousValue = _cAT_TIPO_DOCUMENTO;
                    _cAT_TIPO_DOCUMENTO = value;
                    FixupCAT_TIPO_DOCUMENTO(previousValue);
                }
            }
        }
        private CAT_TIPO_DOCUMENTO _cAT_TIPO_DOCUMENTO;
    
        public virtual SYNC_DOC SYNC_DOC
        {
            get { return _sYNC_DOC; }
            set
            {
                if (!ReferenceEquals(_sYNC_DOC, value))
                {
                    var previousValue = _sYNC_DOC;
                    _sYNC_DOC = value;
                    FixupSYNC_DOC(previousValue);
                }
            }
        }
        private SYNC_DOC _sYNC_DOC;
    
        public virtual GET_EXPEDIENTE GET_EXPEDIENTE
        {
            get { return _gET_EXPEDIENTE; }
            set
            {
                if (!ReferenceEquals(_gET_EXPEDIENTE, value))
                {
                    var previousValue = _gET_EXPEDIENTE;
                    _gET_EXPEDIENTE = value;
                    FixupGET_EXPEDIENTE(previousValue);
                }
            }
        }
        private GET_EXPEDIENTE _gET_EXPEDIENTE;
    
        public virtual GET_TURNO GET_TURNO
        {
            get { return _gET_TURNO; }
            set
            {
                if (!ReferenceEquals(_gET_TURNO, value))
                {
                    var previousValue = _gET_TURNO;
                    _gET_TURNO = value;
                    FixupGET_TURNO(previousValue);
                }
            }
        }
        private GET_TURNO _gET_TURNO;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupCAT_TIPO_DOCUMENTO(CAT_TIPO_DOCUMENTO previousValue)
        {
            if (previousValue != null && previousValue.GET_DOCUMENTOS.Contains(this))
            {
                previousValue.GET_DOCUMENTOS.Remove(this);
            }
    
            if (CAT_TIPO_DOCUMENTO != null)
            {
                if (!CAT_TIPO_DOCUMENTO.GET_DOCUMENTOS.Contains(this))
                {
                    CAT_TIPO_DOCUMENTO.GET_DOCUMENTOS.Add(this);
                }
                if (IdTipoDocumento != CAT_TIPO_DOCUMENTO.IdTipoDocumento)
                {
                    IdTipoDocumento = CAT_TIPO_DOCUMENTO.IdTipoDocumento;
                }
            }
        }
    
        private void FixupSYNC_DOC(SYNC_DOC previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.GET_DOCUMENTOS, this))
            {
                previousValue.GET_DOCUMENTOS = null;
            }
    
            if (SYNC_DOC != null)
            {
                SYNC_DOC.GET_DOCUMENTOS = this;
            }
        }
    
        private void FixupGET_EXPEDIENTE(GET_EXPEDIENTE previousValue)
        {
            if (previousValue != null && previousValue.GET_DOCUMENTOS.Contains(this))
            {
                previousValue.GET_DOCUMENTOS.Remove(this);
            }
    
            if (GET_EXPEDIENTE != null)
            {
                if (!GET_EXPEDIENTE.GET_DOCUMENTOS.Contains(this))
                {
                    GET_EXPEDIENTE.GET_DOCUMENTOS.Add(this);
                }
                if (IdExpediente != GET_EXPEDIENTE.IdExpediente)
                {
                    IdExpediente = GET_EXPEDIENTE.IdExpediente;
                }
            }
        }
    
        private void FixupGET_TURNO(GET_TURNO previousValue)
        {
            if (previousValue != null && previousValue.GET_DOCUMENTOS.Contains(this))
            {
                previousValue.GET_DOCUMENTOS.Remove(this);
            }
    
            if (GET_TURNO != null)
            {
                if (!GET_TURNO.GET_DOCUMENTOS.Contains(this))
                {
                    GET_TURNO.GET_DOCUMENTOS.Add(this);
                }
                if (IdTurno != GET_TURNO.IdTurno)
                {
                    IdTurno = GET_TURNO.IdTurno;
                }
            }
            else if (!_settingFK)
            {
                IdTurno = null;
            }
        }

        #endregion
    }
}
