//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Dal.Pocos
{
    public partial class SYNC_DOC
    {
        #region Primitive Properties
    
        public virtual long IdDocumento
        {
            get { return _idDocumento; }
            set
            {
                if (_idDocumento != value)
                {
                    if (GET_DOCUMENTOS != null && GET_DOCUMENTOS.IdDocumento != value)
                    {
                        GET_DOCUMENTOS = null;
                    }
                    _idDocumento = value;
                }
            }
        }
        private long _idDocumento;
    
        public virtual bool BanderaStatus
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaCarga
        {
            get;
            set;
        }
    
        public virtual string Exception
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual string StatusDoc
        {
            get;
            set;
        }
    
        public virtual string Extencion
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual GET_DOCUMENTOS GET_DOCUMENTOS
        {
            get { return _gET_DOCUMENTOS; }
            set
            {
                if (!ReferenceEquals(_gET_DOCUMENTOS, value))
                {
                    var previousValue = _gET_DOCUMENTOS;
                    _gET_DOCUMENTOS = value;
                    FixupGET_DOCUMENTOS(previousValue);
                }
            }
        }
        private GET_DOCUMENTOS _gET_DOCUMENTOS;

        #endregion
        #region Association Fixup
    
        private void FixupGET_DOCUMENTOS(GET_DOCUMENTOS previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.SYNC_DOC, this))
            {
                previousValue.SYNC_DOC = null;
            }
    
            if (GET_DOCUMENTOS != null)
            {
                GET_DOCUMENTOS.SYNC_DOC = this;
                if (IdDocumento != GET_DOCUMENTOS.IdDocumento)
                {
                    IdDocumento = GET_DOCUMENTOS.IdDocumento;
                }
            }
        }

        #endregion
    }
}
