//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Server.DAL.POCOS
{
    public partial class APP_BANDEJA
    {
        #region Primitive Properties
    
        public virtual long IdTurnoAnt
        {
            get { return _idTurnoAnt; }
            set
            {
                if (_idTurnoAnt != value)
                {
                    if (GET_TURNO != null && GET_TURNO.IdTurno != value)
                    {
                        GET_TURNO = null;
                    }
                    _idTurnoAnt = value;
                }
            }
        }
        private long _idTurnoAnt;
    
        public virtual Nullable<bool> IsSend
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual GET_TURNO GET_TURNO
        {
            get { return _gET_TURNO; }
            set
            {
                if (!ReferenceEquals(_gET_TURNO, value))
                {
                    var previousValue = _gET_TURNO;
                    _gET_TURNO = value;
                    FixupGET_TURNO(previousValue);
                }
            }
        }
        private GET_TURNO _gET_TURNO;

        #endregion
        #region Association Fixup
    
        private void FixupGET_TURNO(GET_TURNO previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.APP_BANDEJA, this))
            {
                previousValue.APP_BANDEJA = null;
            }
    
            if (GET_TURNO != null)
            {
                GET_TURNO.APP_BANDEJA = this;
                if (IdTurnoAnt != GET_TURNO.IdTurno)
                {
                    IdTurnoAnt = GET_TURNO.IdTurno;
                }
            }
        }

        #endregion
    }
}
