//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Server.DAL.POCOS
{
    public partial class CAT_TIPO_DOCUMENTO
    {
        #region Primitive Properties
    
        public virtual long IdTipoDocumento
        {
            get;
            set;
        }
    
        public virtual string TipoDocumentoName
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsActive
        {
            get;
            set;
        }
    
        public virtual Nullable<long> LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsModified
        {
            get;
            set;
        }
    
        public virtual long ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<GET_DOCUMENTOS> GET_DOCUMENTOS
        {
            get
            {
                if (_gET_DOCUMENTOS == null)
                {
                    var newCollection = new FixupCollection<GET_DOCUMENTOS>();
                    newCollection.CollectionChanged += FixupGET_DOCUMENTOS;
                    _gET_DOCUMENTOS = newCollection;
                }
                return _gET_DOCUMENTOS;
            }
            set
            {
                if (!ReferenceEquals(_gET_DOCUMENTOS, value))
                {
                    var previousValue = _gET_DOCUMENTOS as FixupCollection<GET_DOCUMENTOS>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGET_DOCUMENTOS;
                    }
                    _gET_DOCUMENTOS = value;
                    var newValue = value as FixupCollection<GET_DOCUMENTOS>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGET_DOCUMENTOS;
                    }
                }
            }
        }
        private ICollection<GET_DOCUMENTOS> _gET_DOCUMENTOS;

        #endregion
        #region Association Fixup
    
        private void FixupGET_DOCUMENTOS(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (GET_DOCUMENTOS item in e.NewItems)
                {
                    item.CAT_TIPO_DOCUMENTO = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (GET_DOCUMENTOS item in e.OldItems)
                {
                    if (ReferenceEquals(item.CAT_TIPO_DOCUMENTO, this))
                    {
                        item.CAT_TIPO_DOCUMENTO = null;
                    }
                }
            }
        }

        #endregion
    }
}
