//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Server.DAL.POCOS
{
    public partial class GET_FECHA_VENCIMIENTO
    {
        #region Primitive Properties
    
        public virtual long IdFechaVencimiento
        {
            get;
            set;
        }
    
        public virtual long IdAsunto
        {
            get { return _idAsunto; }
            set
            {
                if (_idAsunto != value)
                {
                    if (GET_ASUNTO != null && GET_ASUNTO.IdAsunto != value)
                    {
                        GET_ASUNTO = null;
                    }
                    _idAsunto = value;
                }
            }
        }
        private long _idAsunto;
    
        public virtual System.DateTime FechaVencimiento
        {
            get;
            set;
        }
    
        public virtual System.DateTime FechaCreacion
        {
            get;
            set;
        }
    
        public virtual bool IsActual
        {
            get;
            set;
        }
    
        public virtual bool IsActive
        {
            get;
            set;
        }
    
        public virtual bool IsModified
        {
            get;
            set;
        }
    
        public virtual long LastModifiedDate
        {
            get;
            set;
        }
    
        public virtual long ServerLastModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual GET_ASUNTO GET_ASUNTO
        {
            get { return _gET_ASUNTO; }
            set
            {
                if (!ReferenceEquals(_gET_ASUNTO, value))
                {
                    var previousValue = _gET_ASUNTO;
                    _gET_ASUNTO = value;
                    FixupGET_ASUNTO(previousValue);
                }
            }
        }
        private GET_ASUNTO _gET_ASUNTO;

        #endregion
        #region Association Fixup
    
        private void FixupGET_ASUNTO(GET_ASUNTO previousValue)
        {
            if (previousValue != null && previousValue.GET_FECHA_VENCIMIENTO.Contains(this))
            {
                previousValue.GET_FECHA_VENCIMIENTO.Remove(this);
            }
    
            if (GET_ASUNTO != null)
            {
                if (!GET_ASUNTO.GET_FECHA_VENCIMIENTO.Contains(this))
                {
                    GET_ASUNTO.GET_FECHA_VENCIMIENTO.Add(this);
                }
                if (IdAsunto != GET_ASUNTO.IdAsunto)
                {
                    IdAsunto = GET_ASUNTO.IdAsunto;
                }
            }
        }

        #endregion
    }
}
