//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace SyncService.Server.DAL.POCOS
{
    public partial class MODIFIEDDATA
    {
        #region Primitive Properties
    
        public virtual long IdModifiedData
        {
            get;
            set;
        }
    
        public virtual Nullable<long> IdSincTable
        {
            get { return _idSincTable; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_idSincTable != value)
                    {
                        if (SYNCTABLE != null && SYNCTABLE.IdSincTable != value)
                        {
                            SYNCTABLE = null;
                        }
                        _idSincTable = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<long> _idSincTable;
    
        public virtual Nullable<bool> IsModified
        {
            get;
            set;
        }
    
        public virtual Nullable<long> ServerModifiedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual SYNCTABLE SYNCTABLE
        {
            get { return _sYNCTABLE; }
            set
            {
                if (!ReferenceEquals(_sYNCTABLE, value))
                {
                    var previousValue = _sYNCTABLE;
                    _sYNCTABLE = value;
                    FixupSYNCTABLE(previousValue);
                }
            }
        }
        private SYNCTABLE _sYNCTABLE;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupSYNCTABLE(SYNCTABLE previousValue)
        {
            if (previousValue != null && previousValue.MODIFIEDDATAs.Contains(this))
            {
                previousValue.MODIFIEDDATAs.Remove(this);
            }
    
            if (SYNCTABLE != null)
            {
                if (!SYNCTABLE.MODIFIEDDATAs.Contains(this))
                {
                    SYNCTABLE.MODIFIEDDATAs.Add(this);
                }
                if (IdSincTable != SYNCTABLE.IdSincTable)
                {
                    IdSincTable = SYNCTABLE.IdSincTable;
                }
            }
            else if (!_settingFK)
            {
                IdSincTable = null;
            }
        }

        #endregion
    }
}
